# Default values for services
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  tag: 0.0.0-INTERNAL
  pullPolicy: Always

ImagePullSecret: iusdev
LoggingKey: ""

AppSettingsLocation: 

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabletls: true

global:
  ClientStateName : Consortium
  Environment : Development
  replicaCount: 1
  ingress:
    tlssecret: tls-secret
    host: "***global.ingress.host needs a value***"
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      kubernetes.io/ingress.class: nginx

  additional_env_vars: []